#!/usr/bin/env bash
set -e
set -u
set -o pipefail

while getopts d OPTION "$@"; do
    case $OPTION in
	d)
	    set -x
	    ;;
    esac
done

echo "Compiling and computing classpath (May take a while)"
declare -r GRADLE_CLASSPATH="$(./gradlew :minidns-repl:printClasspath --quiet |\
	tail -n1)"
echo "Classpath computed, starting REPL"

java \
	-Dscala.usejavacp=true \
	-classpath "${GRADLE_CLASSPATH}" \
	scala.tools.nsc.MainGenericRunner \
	-i minidns-repl/scala.repl
